% В функции задаются входные данные для моделирования или обработки
% записанных сигналов
% Входные данные
function [AutoSaveFolder] = az_alg_input_parametric(AutoSaveFolder)
    global Algorithms
    
    %% Параметры алгоритмов
    AutoSaveFolder = sprintf('%s_parametric', AutoSaveFolder);
    Algorithms={
        'pmusic-1ord',      'pmusic-2ord',      'pmusic-4ord',      'pmusic-6ord',      'pmusic-8ord',      'pmusic-10ord',             'pburg-1ord',       'pburg-2ord',       'pburg-4ord',       'pburg-6ord',       'pburg-8ord',       'pburg-10ord',              'peig-1ord',        'peig-2ord',       'peig-4ord',      'peig-6ord',    'peig-8ord',   'peig-10ord',          'pcov-1ord',        'pcov-2ord',       'pcov-4ord',      'pcov-6ord',    'pcov-8ord',   'pcov-10ord',            'pyulear-1ord', 'pyulear-2ord',    'pyulear-4ord',   'pyulear-6ord', 'pyulear-8ord','pyulear-10ord',        ;...
        'Paramet',          'Paramet',          'Paramet',          'Paramet',          'Paramet',          'Paramet',                  'Paramet',          'Paramet',          'Paramet',          'Paramet',          'Paramet',          'Paramet',                  'Paramet',          'Paramet',          'Paramet',       'Paramet',      'Paramet',     'Paramet',             'Paramet',          'Paramet',         'Paramet',        'Paramet',      'Paramet',     'Paramet',               'Paramet',          'Paramet',     'Paramet',         'Paramet',      'Paramet',     'Paramet',         ;...    % [1-исп 0-неисп] Выбор алгоритмов
        1,                  1,                  1,                   1,                  1,                  1,                         1,                  1,                  1,                  1,                  1,                  1,                          1,                  1,                  1,                1,             1,             1,                      1,                  1,                  1,                1,             1,             1,                      1,              1,                 1,                1,              1,             1                       ;...
        'pmusic',           'pmusic',           'pmusic',           'pmusic',           'pmusic',           'pmusic',                   'pburg',            'pburg',            'pburg',            'pburg',            'pburg',            'pburg',                    'peig',            'peig',            'peig',           'peig',         'peig',         'peig',                'pcov',             'pcov',             'pcov',           'pcov',        'pcov',        'pcov',                 'pyulear',      'pyulear',         'pyulear',        'pyulear',      'pyulear',     'pyulear',              ;...
        [],                 [],                 [],                 [],                 [],                 [],                         [],                 [],                 [],                 [],                 [],                 [],                         [],                 [],                 [],               [],            [],             [],                   [],                 [],                  [],               [],             [],            [],                    [],             [],                [],               [],             [],            [],                     ;...
        {1, 'twosided'},    {2, 'twosided'},    {4, 'twosided'},    {6, 'twosided'},    {8, 'twosided'},    {10, 'twosided'},           {1, 'twosided'},   {2, 'twosided'},    {4, 'twosided'},    {6, 'twosided'},    {8, 'twosided'},    {10, 'twosided'},            {1, 'twosided'},   {2, 'twosided'},    {4,'twosided'},   {6,'twosided'},{8,'twosided'}, {10, 'twosided'},      {1, 'twosided'},    {2, 'twosided'},    {4,'twosided'},   {6,'twosided'},  {8,'twosided'},{10, 'twosided'},      {1, 'twosided'},    {2, 'twosided'},    {4,'twosided'},   {6,'twosided'},  {8,'twosided'},{10, 'twosided'}         
        };
    % pburg pcov pyulear peig pmusic
    
end